"""
Unit test to validate evidence construction from selected chunks.

CRITICAL INVARIANT: If selected_chunks > 0, then evidence_count must be >= 1.
Evidence is extracted from the selected chunk texts, NOT from the LLM response.
"""

import pytest
import asyncio
from unittest.mock import patch, MagicMock, AsyncMock
from app.services.rag_service import query_collection


class TestEvidenceConstruction:
    """Test evidence extraction from retrieved chunks."""
    
    @pytest.mark.asyncio
    async def test_evidence_count_matches_chunks(self):
        """
        CRITICAL TEST: If we have selected chunks, evidence must be non-empty.
        Evidence is constructed from chunk texts before LLM is called.
        """
        # Mock ChromaDB collection with realistic data
        mock_collection = MagicMock()
        mock_collection.count.return_value = 10
        mock_collection.query.return_value = {
            "documents": [[
                "1. ARRIVE AT THE OFFICE (8:00 AM)\n- Report to main reception on 3rd floor\n- Bring: ID, offer letter",
                "HYBRID SCHEDULE\n- Work remotely up to 3 days per week\n- Core hours: 10:00 AM - 3:00 PM",
                "EMAIL SIGNATURE SETUP\n- Use Arial 10pt font\n- Include: Name, Title, Phone, Email"
            ]],
            "metadatas": [[
                {"source_file": "onboarding.txt", "chunk": 0},
                {"source_file": "onboarding.txt", "chunk": 1},
                {"source_file": "onboarding.txt", "chunk": 2}
            ]],
            "distances": [[100.0, 150.0, 200.0]],
            "ids": [["chunk_0", "chunk_1", "chunk_2"]]
        }
        
        # Mock embedding response
        mock_embedding = [[0.1] * 768]
        
        # Mock LLM response (should NOT affect evidence construction)
        async def mock_llm_gen():
            yield "8:00 AM at reception"
        
        with patch("app.services.rag_service._get_collection", return_value=mock_collection), \
             patch("app.services.rag_service.embed_texts", new_callable=AsyncMock, return_value=mock_embedding), \
             patch("app.services.rag_service._call_chat_model", return_value=mock_llm_gen()):
            
            # Execute query
            answer_gen, sources, evidence, context, selected_chunks = await query_collection(
                tenant_id="test_tenant",
                question="What time should I arrive?",
                top_k=3,
                mode="full"
            )
            
            # CRITICAL ASSERTIONS
            assert len(selected_chunks) > 0, "Must have selected chunks from retrieval"
            assert len(evidence) >= 1, (
                f"EVIDENCE CONSTRUCTION FAILURE: {len(selected_chunks)} chunks selected "
                f"but only {len(evidence)} evidence extracted. Evidence must be non-empty "
                f"when chunks are available."
            )
            
            # Evidence should come from chunks, not LLM
            for ev in evidence:
                assert isinstance(ev, str), "Evidence must be string"
                assert len(ev) > 0, "Evidence must be non-empty"
            
            # Verify evidence contains content from chunks
            chunk_texts = mock_collection.query.return_value["documents"][0]
            all_chunk_text = " ".join(chunk_texts).lower()
            evidence_found_in_chunks = any(
                any(word in all_chunk_text for word in ev.lower().split()[:3])
                for ev in evidence
            )
            assert evidence_found_in_chunks, (
                "Evidence must be extracted from chunk texts, not generated by LLM"
            )
    
    
    @pytest.mark.asyncio
    async def test_empty_collection_returns_empty_evidence(self):
        """If collection is empty, evidence should be empty (no chunks to extract from)."""
        mock_collection = MagicMock()
        mock_collection.count.return_value = 0
        
        with patch("app.services.rag_service._get_collection", return_value=mock_collection):
            answer_gen, sources, evidence, context, selected_chunks = await query_collection(
                tenant_id="test_tenant",
                question="What time should I arrive?",
                top_k=3,
                mode="full"
            )
            
            # Empty collection = no chunks = no evidence = empty response
            assert len(selected_chunks) == 0, "No chunks should be selected from empty collection"
            assert len(evidence) == 0, "No evidence should exist for empty collection"
    
    
    @pytest.mark.asyncio
    async def test_evidence_extraction_fallback(self):
        """Even if evidence extraction fails, fallback ensures non-empty evidence when chunks exist."""
        mock_collection = MagicMock()
        mock_collection.count.return_value = 5
        mock_collection.query.return_value = {
            "documents": [["Single chunk with content"]],
            "metadatas": [[{"source_file": "test.txt", "chunk": 0}]],
            "distances": [[100.0]],
            "ids": [["chunk_0"]]
        }
        
        mock_embedding = [[0.1] * 768]
        
        async def mock_llm_gen():
            yield "Response"
        
        with patch("app.services.rag_service._get_collection", return_value=mock_collection), \
             patch("app.services.rag_service.embed_texts", new_callable=AsyncMock, return_value=mock_embedding), \
             patch("app.services.rag_service._call_chat_model", return_value=mock_llm_gen()):
            
            answer_gen, sources, evidence, context, selected_chunks = await query_collection(
                tenant_id="test_tenant",
                question="Random question",
                top_k=1,
                mode="full"
            )
            
            # INVARIANT: selected_chunks > 0 => evidence_count >= 1
            if len(selected_chunks) > 0:
                assert len(evidence) >= 1, (
                    f"INVARIANT VIOLATION: {len(selected_chunks)} chunks but {len(evidence)} evidence. "
                    f"Fallback should guarantee at least one evidence item."
                )


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
